---
theme: jekyll-theme-cayman

future: true

title: Ishu Dharmedra Garg
description: Final Year DD, CSE, IIT Madras

social_links:
  github: "https://github.com/ash567/"
  linkedin: "https://www.linkedin.com/in/ishugarg/"
  email: "ishugarg567@gmail.com"
---
